### ISSUE TITLE
Compiled toxcore but libraries not found when trying to compile Toxic

### ISSUE THREAD

**Issue by alexkaskasoli** [JFreegman/toxic#299]
I've successfully compiled `toxcore` and can testify that the libraries are in `/usr/local/lib`:
```
libsodium.a
libsodium.la
libsodium.so
libsodium.so.13
libsodium.so.13.0.2
libtoxav.a
libtoxav.la
libtoxav.so
libtoxav.so.0
libtoxav.so.0.0.0
libtoxcore.a
libtoxcore.la
libtoxcore.so
libtoxcore.so.0
libtoxcore.so.0.0.0
libtoxdns.a
libtoxdns.la
libtoxdns.so
libtoxdns.so.0
libtoxdns.so.0.0.0
libtoxencryptsave.a
libtoxencryptsave.la
libtoxencryptsave.so
libtoxencryptsave.so.0
libtoxencryptsave.so.0.0.0
```

But when trying to `make` Toxic I get:
```
/home/user/Applications/toxic/cfg/checks/av.mk:19: WARNING -- Toxic will be compiled without audio support
/home/user/Applications/toxic/cfg/checks/av.mk:20: WARNING -- You need these libraries for audio support
/home/user/Applications/toxic/cfg/checks/av.mk:21: WARNING -- libtoxav
/home/user/Applications/toxic/cfg/checks/sound_notifications.mk:19: WARNING -- Toxic will be compiled without sound notifications support
/home/user/Applications/toxic/cfg/checks/sound_notifications.mk:20: WARNING -- You need these libraries for sound notifications support
/home/user/Applications/toxic/cfg/checks/sound_notifications.mk:21: WARNING -- freealut
/home/user/Applications/toxic/cfg/checks/check_features.mk:35: ERROR -- Cannot compile Toxic
/home/user/Applications/toxic/cfg/checks/check_features.mk:36: ERROR -- You need these libraries
/home/user/Applications/toxic/cfg/checks/check_features.mk:37: ERROR -- libtoxcore
/home/user/Applications/toxic/cfg/checks/check_features.mk:38: *** ERROR.  Stop.
```
NB: 3.17.7-300 Fedora 21

**Comment by Ansa89** [comment]
What is the output of `pkg-config --libs libtoxcore`?

**Comment by alexkaskasoli** [comment]
@Ansa89 Good call, it appears the libraries were not properly installed:

`Package libtoxcore was not found in the pkg-config search path.`
`Perhaps you should add the directory containing 'libtoxcore.pc'`
`to the PKG_CONFIG_PATH environment variable`
`No package 'libtoxcore' found`

How can I fix this manually? (I've rebuilt and installed toxcore again since then, same problem. It seems it doesn't install properly on my Fedora box)

**Comment by jin-eld** [comment]
Hi,

On Wed, Mar 04, 2015 at 09:51:20AM -0800, Alexandre Kaskasoli wrote:
> How can I fix this manually? (I've rebuilt and installed toxcore again since
> then, same problem. It seems it doesn't install properly on my Fedora box)

did you for sure run "make install" in toxcore? Did you specify any
custom --prefix when running toxcore's configure?

Then also check /usr/local/lib64/pkgconfig - it is possible that
pkg-config will not look in the local dirs by default, in this case you might
want to set PKG_CONFIG_PATH

Alternatively, I submitted a spec file yesterday which I have tested on
Fedora, so you could "make dist" your tox library and process the
resulting tarball using:

rpmbuild -tb tox-0.0.0.tar.gz

...in oder to get an rpm that you could install system wide.

If you would like to try that I suggest that you:

yum install rpmdevtools

And then under your user account do:

rpmdev-setuptree

(never build rpms as root!)

The rpm package will install to the system directories which are searched
by toxic build scripts by default.

Kind regards,
Jin

**Comment by Ansa89** [comment]
@alexkaskasoli can you post the output of `echo $PKG_CONFIG_PATH`?
Just curious to see which paths are searched by pkg-config.

**Comment by hardlyeven** [comment]
Hey, I'm was having the same issue on Fedora 21.  My `echo $PKG_CONFIG_PATH` and `pkg-config --libs libtoxcore` returned empty.  Thanks Jin and Ansa for the help, pkg-config was not looking in /usr/local/lib, [this](http://unix.stackexchange.com/questions/110856/something-is-terribly-wrong-with-pkg-config) helped me export /usr/local/lib to PKG_CONFIG_DIR but it doesn't seem like a permanent solution. And even though I managed to make without errors (including no warnings about no AV support), when I run toxic, I just get `./toxic: error while loading shared libraries: libtoxav.so.0: cannot open shared object file: No such file or directory`. weird too because pkg-config seems to find it. 
```
$ pkg-config --libs libtoxav 
-L/usr/local/lib -ltoxav -lopus -lvpx -lm -ltoxdns -ltoxencryptsave -ltoxcore -lsodium -lm -lpthread 
```
I `DISABLE_AV=1` and it works, but I'd love to compile with AV. Any Ideas?

**Comment by jin-eld** [comment]
On Fri, Mar 06, 2015 at 10:19:25AM -0800, jlo wrote:
> libraries: libtoxav.so.0: cannot open shared object file: No such file or
> directory. weird too because pkg-config seems to find it.

This is because /usr/local/lib is not listed anywhere under
/etc/ld.so.conf.d/  - meaning, Fedora is not looking in /usr/local by
default.

Basically you will have this problem with any package that is not
installed system wide.

I personally prefer not to install unpackaged software system wide at all,
I keep such things in a alternative "sysroot" in my home directory, where
I install all dependencies etc. by using the --prefix= configure option.

I then have the appropraite PATH and LD_LIBRARY_PATH settings in my .bashrc

I guess it's up to you which way you like to go, either make your system
aware of /usr/local/*, use the above approach in your users directory or
roll an rpm of tox-core which should be fairly simple now. The only thing
to look out for with the rpm is, that you'll need bump the Release tag each
time you build in order to be able to upgrade, or alternatively yum remove
the old version prior to installing the new one. Since there are no official 
released versions of libtoxcore yet, thus the versions in the spec file stay 
the same when you build it from git.
