### ISSUE TITLE
Implement Tox Client Standard concerning the avatars

### ISSUE THREAD

**Issue by ovalseven8** [JFreegman/toxic#365]
> 2.3.5 Clients must display avatars at a 1:1 aspect ratio.

Not relevant for Toxic at the moment because the display of avatars is not supported yet.

> 2.3.6 A client may only transmit avatars with an aspect ratio of 1:1. If the user has chosen a non-square avatar, the client must transmit the square portion of the avatar displayed to the user. **In the case that the user's client doesn't display avatars, the client must pad the avatar evenly on two sides with transparent rectangles, in order to create a square.**

That's relevant for Toxic. 
What's possible as well is that users are only able to set a square avatar. So, you wouldn't need to pad avatars.

**Comment by xeruf** [comment]
Well, let's pick this back up and check compatibility since toxic supports avatars now.

Unfortunately, the feature does not work for me - I tried to set `tox.avatar_path="/Path/to/gendry.png"` with the following PNG, which is far from the size limit:
![gendry](https://user-images.githubusercontent.com/13354331/151077582-ee0a33ce-cad1-46b2-8768-274efcba5176.png)
But get

    Failed to set avatar. Avatars must be in PNG format and may not exceed 65536 bytes.
    
Okay, figured it out while typing - I forgot a `/` at the beginning of the path.
Would be nice if the error message would be different for an invalid file path.

**Comment by JFreegman** [comment]
This has been implemented
