### ISSUE TITLE
New debian package

### ISSUE THREAD

**Issue by lweberk** [JFreegman/toxic#448]
Having trouble to find an up-to-date package, I took the liberty of creating a git-buildpackage based packaging repository; https://github.com/lweberk/dpkg-toxic

Currently builds upstream v0.7.2 nicely against debian stretch (which is frozen for release as we speak). Requires the inclusion of the official tox repository `https://pkg.tox.chat/debian/stable/jessie` for;
`libtoxav-toktok-dev`
`libtoxcore-toktok-dev`
`libtoxdns-toktok-dev`
`libtoxencryptsave-toktok-dev`

Had some trouble getting my head around the workflow of downstream packaging directly from upstream git. So not 100% sure everything is correct.

A warning I would like to get rid of is the fact that the .desktop file includes a mime type definition, but no argument passing placeholder in the exec statement. Opened #447 for this point.

**Comment by Encrypt** [comment]
Hi @lweberk,

Well, there are already Debian Jessie packages of toxic... but in the "nightly" branch.
I guess that's why you didn't manage to install it.

Here is the proof:
  - https://pkg.tox.chat/debian/dists/nightly/jessie/binary-amd64/Packages
  - https://build.tox.chat/job/toxic_pkg_linux_deb_shared_jessie_x86-64_nightly_release/

To install the nightly repository, as mentioned on https://tox.chat/download.html#gnulinux, you have to run the command: `echo "deb https://pkg.tox.chat/debian nightly $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list`

Finally, if you wish to have a look at how the packages are built for Debian, check out Toxdeb: https://pkg.tox.chat/debian/dists/nightly/jessie/binary-amd64/Packages

Cheers!

**Comment by lweberk** [comment]
There are a number of minor releases between the stable and nightly repositories. Are they all to be seen as unstable?
