### ISSUE TITLE
Way to auto-accept group invites

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#465]
Due to the way tox group chats are currently implemented you need to interract with a bot. Is there any way  to automize this ?

**Comment by JFreegman** [comment]
There is no way to auto-accept group invites, and I don't plan on implementing this

**Comment by ghost** [comment]
Any specific reason ? Are you willing to accept pull requests ?

**Comment by JFreegman** [comment]
It's a potential security liability, as it would give someone on your friend list the ability to expose your IP address to a group of strangers without your consent (among other things). In order to comply with the TCS you would need to make it an option, and have it turned off by default. I'd be willing to accept a pull request.

**Comment by ghost** [comment]
Ohh ok I see.
