### ISSUE TITLE
Need help in saving names for friends list.

### ISSUE THREAD

**Issue by blprasad** [JFreegman/toxic#521]
Hi all ,
I am trying to run toxic on my Pi board, with matrix keypad and monochrome lcd.
Problem I am facing is, I am using  friendlist_NickChange();  function for setting names for friends list names ,it's setting names temporarily , I mean when I reboot the system,I am unable to see the previously set names.Friend list names are showing empty ,could someone help me, how to save the Friends.list[].name until I reset the names . 
I tried  setfriendname(); prior but I could not use it successfully ,I don't know which is the correct call to do the job.

thanks in advance.

**Comment by JFreegman** [comment]
The reason they set back to the default is because every time a contact goes online (e.g. when you restart the client) they send you all of their info and the name you previously set gets overwritten. Toxic doesn't have support for contact aliases so there is no simple way to get around this. You would need to use a client-specific save file, which is the reason I never got around to implemented this feature.

**Comment by blprasad** [comment]
OK , got one more question to  be more clear about my understanding, the total number of added contacts and their corresponding toxids are saved and persist on each restart,but only their corresponding names are updated online am I correct?
thanks for your previous comment

**Comment by JFreegman** [comment]
That's correct
