### ISSUE TITLE
Other clients interpret avatar as a regular file transfer after a reconnect

### ISSUE THREAD

**Issue by moorchegue** [JFreegman/toxic#529]
When `avatar_path` is defined in toxic.conf, and there's a connectivity issue (connection is lost and then re-established again), the other party receives a file transfer request with the avatar file.

This is a thing with at least qTox (on Mac) and jTox (Sailfish) and several versions of Toxic up to 0.8.3.

Depending on the network stability it can be anywhere from kinda funny to extremely annoying.

Here's a jTox screenshot as an example: https://wtf.roflcopter.fr/pics/zJeTBdyI/XLov98mj.png

**Comment by JFreegman** [comment]
This is happening because the receiving clients are not differentiating between normal files and avatar files when they get a file request. You can see in Toxic's source that it sends avatars with the FILE_KIND_AVATAR parameter: https://github.com/JFreegman/toxic/blob/master/src/avatars.c#L68

When a client receives a file transfer request it needs to check that parameter, like this: https://github.com/JFreegman/toxic/blob/master/src/windows.c#L267

edit: I was unable to reproduce this bug with qtox v1.16.3 on Linux. Toxic ignores avatars all-together, so if you're getting avatar file requests on Toxic, that means the sending client is not correctly setting the file kind.

**Comment by moorchegue** [comment]
Transfer requests only pop up in other clients. Toxic itself is unaffected by this, as far as I can tell. No other combination of clients I've tried so far produced the same effect, only Toxic -> qTox / jTox.

It only happens after a reconnection. It doesn't happen on the first run, so if there's no network issues, this never occurs. Is it possible that this case is somehow different from either Toxic's or other clients' perspective?

I also couldn't reproduce this with qTox on Linux. It seems to happen on the OS X version of it though. I don't own a Mac, so I can't really verify / help to debug that. But I can run experiments with my jTox since it has the same effect on it. If there's anything I can do to narrow down the conditions under which it happens or anything else, I'd be happy to help.

**Comment by JFreegman** [comment]
I just double checked with some debugging tools, and toxic only sends avatar file types after a reconnect. The problem must be on the receiving clients not differentiating avatar files from normal files. What they're supposed to do is check the inbound avatar file's hash and ignore the transfer if the hash matches the one they already have stored, which is generally the case after a network hickup. They shouldn't be treating it like a normal file transfer.

Are you able to reproduce this problem with utox? It's possible that the jTox developer copied some of qTox's avatar code without understanding it. Also, which versions of jTox and qTox are you using respectively?

**Comment by JFreegman** [comment]
It was a toxic bug after all, fixed in: https://github.com/TokTok/toxic/pull/126
