### ISSUE TITLE
Why two repos?

### ISSUE THREAD

**Issue by jubalh** [JFreegman/toxic#572]
I'm having difficulty making sense of this.
It seems you have:
* https://github.com/JFreegman/toxic
* https://github.com/toktok/toxic

And in the former you ask people to create PRs on the latter. But still doing PRs and creating issues on the former is not disabled. So people create issues and PRs on both. Isn't that getting confusing?

Which one should be regarded as the official repo?

I assume that this has grown historically and that the first repo was where you started developing.
Later on it probably should have been transferred instead of forked from toktok.
Personally I would use https://github.com/toktok/toxic and ask GitHub to delete the `forked from JFreegman/toxic` mark.

**Comment by JFreegman** [comment]
JFreegman/toxic is the original repo, and toktok/toxic is the toktok organization's fork of my repo. I currently contribute to/develop on the toktok fork and keep my own repo up to date with it. However that may not always be the case in the future, and I still consider my own repo to be the "official" one. 

I wasn't aware that github allowed us to block or disable PR's. But I wouldn't want to do that anyways, because I sometimes do PR's on this repo in order to utilize the integrated analysis/testing tools before requesting a review on the toktok repo.

From a user or distro maintainer's point of view you can use the master branch from either one. From a developer's point of view you should make PR's on toktok/toxic. Issues don't really matter, but it's probably best to keep them all in the same place on the current development fork.

**Comment by jubalh** [comment]
Thanks for the clarification.
